### ISSUE TITLE
Bump linux mongo driver to 1.16.0?

### ISSUE THREAD

**Issue by Sanic** [robcog-iai/UMongoC#1]
Hi @andreihaidu 
Could you please bump up the linux driver to 1.16.0 so that it is inline with the Windows version?
The API has changed between these versions so currently you get an error on Linux:

````
USemLog/Source/USemLog/Private/Editor/SLAssetDBHandler.cpp:471:2: error: unknown type name 'mongoc_gridfs_bucket_t'; did you mean 'mongoc_gridfs_file_t'?
        mongoc_gridfs_bucket_t *bucket;
        ^~~~~~~~~~~~~~~~~~~~~~
        mongoc_gridfs_file_t

````

**Comment by andreihaidu** [comment]
@Sanic the latest PR from one of my students might have solved your issue :)
